version: 0.2

phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g pm2
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Compiling the Node.js code
      - pm2 start app.js -i 2
